### ISSUE TITLE
Please remove useless files

### ISSUE THREAD

**Issue by pcav** [UdK-VPT/Open_eQuarter#68]
.gitignore, /backups, probably pdf, etc.
Thanks.

**Comment by MaxUdk** [comment]
Done so far.

**Comment by pcav** [comment]
Thanks. Please upload a new version (without server flag).

**Comment by pcav** [comment]
Please check again: more stuff is left (e.g. .Rhistory, etc.). Only code should be there.
Thanks.

**Comment by MaxUdk** [comment]
Hello Paolo,

I think I’ve got it. A new cleaner version is uploaded without the server flag. Furthermore I cleaned up the repo as far as I could do without discussing the purpose of this and that with the other team members. 

Regards

Werner




Dipl-.Ing. Architekt Werner Kaul

Einsteinufer 43
10587 Berlin 
Germany

Fon: +49 30 3185-2279
Fax:   +49 30 3185-2918
Mobil: +49 172 2136077
eMail:  werner.kaul@udk-berlin.de <mailto:werner.kaul@udk-berlin.de>

**Comment by pcav** [comment]
Il 07/04/2017 11:07, MaxUdk ha scritto:
> Hello Paolo,
> 
> I think I’ve got it. A new cleaner version is uploaded without the
> server flag. Furthermore I cleaned up the repo as far as I could do
> without discussing the purpose of this and that with the other team
> members.

Thanks, now published. Hope this did not bothered you too much, and I'm
sure it will improve the general quality of the plugin ecosystem.
All the best, and thanks for the fast response.

-- 
Paolo Cavallini - www.faunalia.eu
QGIS & PostGIS courses: http://www.faunalia.eu/training.html
https://www.google.com/trends/explore?date=all&geo=IT&q=qgis,arcgis

**Comment by MaxUdk** [comment]
Thank you for your assistance. 

Have a nice weekend.

Werner






Dipl-.Ing. Architekt Werner Kaul

Einsteinufer 43
10587 Berlin 
Germany

Fon: +49 30 3185-2279
Fax:   +49 30 3185-2918
Mobil: +49 172 2136077
eMail:  werner.kaul@udk-berlin.de <mailto:werner.kaul@udk-berlin.de>

**Comment by MaxUdk** [comment]
Hello Paolo,

Open eQuarter is still not available in the qgis plugin repo. Did I miss anything in the sharing process?

Regards Werner





Dipl-.Ing. Architekt Werner Kaul

Einsteinufer 43
10587 Berlin 
Germany

Fon: +49 30 3185-2279
Fax:   +49 30 3185-2918
Mobil: +49 172 2136077
eMail:  werner.kaul@udk-berlin.de <mailto:werner.kaul@udk-berlin.de>
